### PR TITLE
Fix (trait?) methods that take + return Self

### LINKED ISSUE #40: Can't use #[faux::methods] on an impl Clone for X {} block
```rust
struct Foo;
#[faux::methods]
impl Clone for Foo {
    fn clone(&self) -> Self {
        Foo
    }
}
```

```
error[E0308]: mismatched types
 --> src/lib.rs:3:1
  |
3 | #[faux::methods]
  | ^^^^^^^^^^^^^^^^ expected struct `_FauxOriginal_Foo`, found struct `Foo`
  |
```
This happens whether or not I manually change `Self -> Foo`. Looking at the expanded source, I think it's because the `methods` macro unconditionally wraps the generated match in `MaybeFaux::Real`, even though it should wrap the result of `call_mock` in `MaybeFaux::Faux`

### PR DESCRIPTION
**Pull request by coolreader18**
fixes #40

### CODE REVIEW

**Comment by coolreader18** [comment]
Ah, looks like you got it!

**Comment by nrxus** [comment]
Ah! I decided to use my lunch break to fix it up, and didn't see this pending PR, sorry!

I see you also did some other clean ups though so I will take those (:

**Comment by coolreader18** [comment]
No worries! I'll rebase this.

**Comment by nrxus** [comment]
I didn't know about `syn::parse_quote`, thanks a lot!

**Pull request merged**
